# Generated by Django 3.2.6 on 2021-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='add_teacher',
            name='select_skills',
            field=models.ManyToManyField(to='teacher.Skills'),
        ),
    ]
