# Generated by Django 3.2.6 on 2021-10-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20211006_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_subject',
            name='select_skills',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
